# Generated by Django 4.2.2 on 2023-06-29 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eBoard_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.ImageField(null=True, upload_to="uploads/")),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "receiver",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student", "Student"),
                            ("staff", "Staff"),
                            ("staff and student", "Staff and Student"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notifications",
                "db_table": "Notifications",
            },
        ),
    ]
