# Generated by Django 4.2.2 on 2023-07-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eBoard_auth", "0003_alter_notification_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
