# Generated by Django 4.2.2 on 2024-02-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eBoard_auth", "0004_alter_notification_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(db_index=True, default="", max_length=14),
            preserve_default=False,
        ),
    ]
